name = "local-market"
main = "src/index.ts"
compatibility_date = "2026-09-15"

[observability]
enabled = true

[assets]
directory = "../../apps/web/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "bazar_db"
database_id = "ffab4dea-492f-4789-8382-324ab1209c2a"

[secrets]
required = ["IMAGEKIT_PRIVATE_KEY"]
